AWSTemplateFormatVersion: 2010-09-09
Description: A CloudFormation template that creates a role for authenticating with OpsWorks.Co AWS integrations.
Parameters:
  Permissions:
    Type: String
    Default: AdministratorAccess
    AllowedValues:
      - AdministratorAccess
      - ReadOnlyAccess
    Description: Choose required permissions for newly created AIM Role

Resources:
  OpsWorksCoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: OpsWorksCoRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            "AWS": "734274005629" # This needs to be updated
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId: !Select [2, !Split ['/', !Ref AWS::StackId]]
      Path: /
      ManagedPolicyArns:
        - !Join ["/", ["arn:aws:iam::aws:policy", !Ref "Permissions"]]

Outputs:
  OpsWorksCoRoleARN:
    Description: OpsWorksCo Role ARN to use STS calls
    Value: !GetAtt OpsWorksCoRole.Arn
  ExternalID:
    Description: ExternalID to use STS calls
    Value: !Select [2, !Split ['/', !Ref AWS::StackId]]
